### ISSUE TITLE
Do we need `--trusted-block-*` flags for the CLI `gen-oracle-key`?

### ISSUE THREAD

**Issue by youngjoon-lee** [medibloc/panacea-oracle#44]
Related with https://github.com/medibloc/panacea-core/issues/557

It seems that we don't need trusted block info for generating an oracle key, seal it, and store it to the disk. If I understand it correctly, the only reason why we get `--trusted-block-*` flags is for initializing verifiedQueryClient in advance, so that it can be used when we do `oracled start`. If so, what do you think about specifying trusted block info when we do `oracled start`, by flags or a toml file?
Because we're getting trusted block info for `gen-oracle-key`, we always need a running chain whenever we do `gen-oracle-key`. It's not a big issue in the mainnet. But when we test the entire system in local, it makes bootstrapping complicated.
Also, it's not intuitive that we need trusted block info for `gen-oracle-key`, because the `gen-oracle-key` operation doesn't require any communication with the chain.

**Comment by gyuguen** [comment]
We need to trustedBlockInfo when `gen-oracle-key` and `register-oracle` CMD.
Because if the oracle can change TrustedBlockInfo at startup, then the oracle can obtain the information with the forged blockchain.
Forged blockchains can pose serious security risks.(OraclePrivKey stealing, fake sales, etc...)

**Comment by youngjoon-lee** [comment]
Good point. Then, let's keep our strategy as it is. I've forgotten about it. I'll close this ticket and other relevant tickets.

**Comment by youngjoon-lee** [comment]
I just reopened this issue. Let's add a comment in the proto file or so, about what @gyuguen explained in the https://github.com/medibloc/panacea-oracle/issues/44#issuecomment-1356961466

**Comment by H4NLee** [comment]
I think we can even not using a verified query client (no need of trusted-block-*).

Since the oracle private key is shared through unique ID-based encryption/decryption and remote report verification, the key will not be leaked. If someone use a different binary to steal the oracle private key, they cannot access the oracle private key at that moment.

However, when a verified query client is not used, it can be a problem with the `get-secret-key` handler. If all the information obtained from panacea is manipulated (when the consumer is manipulated after copying the data deal and certificate information from the real panacea), oracle can provide the secret key to the fake consumer. This is due to the fact that the oracle information from panacea must be true, and this can also be solved by providing consumers with a way to acquire data in a different way.

If I'm missing some points, please let me know.

**Comment by gyuguen** [comment]
I think it could be manipulated to use a different uniqueID with a forget blockchain.
It's not implemented yet, but it seems possible to migrate the OraclePrivKey to a tampred with Oracle.

And I agree `get-secret-key` part.

**Comment by youngjoon-lee** [comment]
Yes. As @H4NLee commented, I agree that using light client is mandatory. 
In regard to the way how we specify a trusted block info to the oracle, I thought we can specify it in the `config.toml`, so that it can be read by `oracled start`. But, as @gyuguen commented in https://github.com/medibloc/panacea-oracle/issues/44#issuecomment-1356961466, using `config.toml` has a security vulnerability because a human can specify fake trusted block info whenever he wants. So, I think we don't need to change our current approach. But we need to add some comments in the proto files, so that someone can understand it correctly in the future.

**Comment by H4NLee** [comment]
> I think it could be manipulated to use a different uniqueID with a forged blockchain.
It's not implemented yet, but it seems possible to migrate the OraclePrivKey to a tampred with Oracle.

You probably consider the upgrade and migration of oracle private key, right?
If we use different pair of oracle key(also generated in SGX, must store unique ID, oracle pub key, remote report) when upgrade, I think we don't have to care about the fake panacea. We can discuss this when we design upgrade oracle
